services:
  - type: web
    name: aurafy-music-player
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: GROQ_API_KEY
        sync: false
